name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  release:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          # This fetches the entire Git history so that Changesets can generate changelogs with the correct commits.
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24.8
          npm-version: 11.6
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1.7.0
        with:
          commitMode: github-api 
          title: "chore: version packages"
          commit: "chore: version packages"
          version: bunx changeset version
          publish: bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  snapshot:
    if: github.event_name == 'workflow_dispatch'
    name: Release query snapshot version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.8
          npm-version: 11.6
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Publish snapshot
        continue-on-error: true
        run: |
          snapshot=$(printf '%s' "$GITHUB_REF_NAME" | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          bunx changeset version --no-git-tag --snapshot $snapshot
          bunx changeset publish --no-git-tag --snapshot $snapshot --tag $snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
