name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This fetches the entire Git history so that Changesets can generate changelogs with the correct commits.
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: bun run changeset version
          publish: bun run build && bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  snapshot:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Create release pull request or publish to npm
        continue-on-error: true
        run: |
          snapshot=$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          bun run changeset version --no-git-tag --snapshot $snapshot
          bun run build && bun run changeset publish --no-git-tag --snapshot $snapshot --tag $snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}